# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hoctiengnhatglobal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hoctiengnhatglobal
  pod 'SQLite.swift'
  pod 'OSSSpeechKit'
  pod 'SwiftKeychainWrapper'
  pod 'RxCocoa'
  pod 'CountdownLabel'
end
